dependencies:
- name: exposecontroller
  version: 2.3.89
  repository: https://s1.puzhentan.com/jenkins-x
  alias: expose
- name: exposecontroller
  version: 2.3.89
  repository: https://s1.puzhentan.com/jenkins-x
  alias: cleanup
